### ISSUE TITLE
related but different package 

### ISSUE THREAD

**Issue by sa-lee** [emitanaka/edibble#1]
https://csoneson.github.io/ExploreModelMatrix/index.html

**Comment by emitanaka** [comment]
Thanks Stewart! I remember seeing this one before and looked like it can lead to a good development for people to grasp better about factorial structure (esp. with interaction effects)

**Comment by sa-lee** [comment]
definitely seems like a special case to the ideas in your package but might have some useful ideas for vis :)

**Comment by emitanaka** [comment]
I'll be keen to see their development on it!
