### ISSUE TITLE
Some errors on example code

### ISSUE THREAD

**Issue by cbud** [emitanaka/edibble#31]
Example code gets error i:

> out <- des %>% 
+   record_vars(student = c(exam_mark,
+                           quiz1_mark,
+                           quiz2_mark,
+                           gender),
+               class = c(room,
+                         teacher)) %>%
+   expect_vars( exam_mark = to_be_numeric(with_value(between = c(0, 100))),
+                quiz1_mark = to_be_integer(with_value(between = c(0, 15))),
+                quiz2_mark = to_be_integer(with_value(between = c(0, 30))),
+                gender = to_be_factor(levels = c("female", "male", "non-binary", "unknown")),
+                teacher = to_be_character(length = with_value("<=", 100)),
+                room = to_be_character(length = with_value(">=", 1))) %>% 
+   serve_table()
Error: Conditions must have named data fields
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Conditions must have named data fields
Backtrace:
  1. `%>%`(...)
 10. edibble::record_vars(...)
 11. edibble::set_rcrds(.edibble, ..., .name_repair)
 12. rlang::abort("The units", vnames_unit[!ind], "are not defined in the design.")
 13. rlang::error_cnd(...)

**Comment by cbud** [comment]
During installation got some errors similar to this: Rd warning: C:/Users/buddenhagenc/AppData/Local/Temp/7/Rtmp4QefpQ/R.INSTALL49fc17142ca3/edibble/man/start_design.Rd:23: missing link 'record_vars'

Here is the output from error

> rlang::last_error()
<error/vctrs_error_incompatible_type>
Can't combine `..1` <unit(4)> and `..2` <character>.
Backtrace:
  1. (function (x, ...) ...
  6. base::lapply(...)
  7. FUN(X[[i]], ...)
 11. vctrs:::`==.vctrs_vctr`(y, "NA")
 12. vctrs::vec_equal(e1, e2)
 13. vctrs:::vec_cast_common_params(!!!args, .to = .ptype, .df_fallback = DF_FALLBACK_quiet)
 14. vctrs:::vec_cast_common_opts(..., .to = .to, .opts = opts)
 16. vctrs::vec_default_ptype2(...)
 17. vctrs::stop_incompatible_type(...)
 18. vctrs:::stop_incompatible(...)
 19. vctrs:::stop_vctrs(...)

**Comment by emitanaka** [comment]
Thanks! This is related to #26 and the API was wrongly mapped. It's fixed now but likely to change this set out as mentioned in #26
