### ISSUE TITLE
Add more classical named designs

### ISSUE THREAD

**Issue by emitanaka** [emitanaka/edibble#4]
- [x] Balance incomplete block design (is this possible?)
- [ ] Alpha designs - Patterson and Williams(1976) 
- [ ] Cyclic designs - John, J.A. (1981) Efficient Cyclic Design
- [ ] Augmented block designs
- [x] Latin square design
- [x] Graeco-Latin square design
- [ ] Lattice designs
- [x] Strip plot design
- [x] Youden square design
- [x] Factorial design

**Comment by nfultz** [comment]
- [ ]  Fractional Factorial design
