### ISSUE TITLE
Should autoplot() be exported?

### ISSUE THREAD

**Issue by adamhsparks** [emitanaka/edibble#72]
I've used `autoplot()` in [{hagis}](https://github.com/openplantpathology/hagis) and re-exported it for ease of use by the end-user and I noted that it isn't with {edibble}. Is this something you'd consider?

**Comment by emitanaka** [comment]
It's actually in the deggust package! 

https://github.com/emitanaka/deggust

**Comment by adamhsparks** [comment]
ah, hm. OK, I guess I'd missed that because I was just looking at a section of one of the tutorials and didn't realise I needed to load that package as well. That explains it then. 🙏

**Comment by emitanaka** [comment]
I could definitely improve the documentation! (How I wish I can have more hands and time!)

**Comment by adamhsparks** [comment]
I completely understand.
